### ISSUE TITLE
V2 - Todos

### ISSUE THREAD

**Issue by NicoLaval** [InseeFr/Lunatic#250]
- [x] Fix Textarea
- [x] Fix filters
- [x] missing into loops
- [x] cleaning into loops
- [x] fix execute compilation into loops
- [x] improve gha to deploy v2-master storybook
- [x] resizing
- [x] re activate md support
- [x] fix pagination - back to loop
- [x] Tables
- [x] Fix Loop when pagination is not 1 question per page
- [x] fix cleaning: when a variable is cleaning because of missing, cleaning handling is not done
- [x] Bug expression in Loops
- [x] `getState` to improve
- [x] #299
    - [x] check if xAxis & yAxis are really calculated into state
    - [x] conditionFilter
    - [ ] pagination
    - [ ] Pairwise block model
- [x] #205 
- [ ] #297

**Comment by ddecrulle** [comment]
- [ ] a `getData` function, `getState` gives variables but is not well formatted and can't be reinjected into `useLunatic` throughout `data` parameter
- [ ] a `goPage(page)` function in order to directly jump into a given page
   - [ ] check that the page is reachable with the current data (filter etc ...)
   - [ ] support subpage
   - [ ] support iteration
- [ ] Breadcrumb component

**Comment by AnneHuSKa** [comment]
To do : https://github.com/InseeFr/Lunatic/issues/297
