### ISSUE TITLE
Validation of New Stable Lunatic version

### ISSUE THREAD

**Issue by laurentC35** [InseeFr/Lunatic#655]
Validation of new stable Lunatic with [Storybook-beta](https://inseefr.github.io/Lunatic/storybook-beta)

PR associated : https://github.com/InseeFr/Lunatic/pull/652

**Comment by AnneHuSKa** [comment]
Questionnaires Familles et SD (https://github.com/InseeFr/Lunatic/issues/642) : ok
Questionnaire VPP :
- Réponse Oui à "Kish" envoie à adresse
- Retour
- Réponse Non à "Kish" renvoie à Kish_web puis Kish_telephone puis affiche "Savez-vous si null a voyagé en juin, juillet ou août 2023 ?"
- Retour
- Réponse Oui à "Kish" envoie à "Savez-vous si null a voyagé en juin, juillet ou août 2023 ?"
Un souci de conception ? le souci est également présent sur la version Stromae : 2.4.6 | Lunatic : 2.4.9

**Comment by ddecrulle** [comment]
Okay, I think I've got it and it's not a design issue.

What happens in the questionnaire is that there's a succession of filters. 

When you modify Kish there's a cleaning of Kish_Web because the question that collects Kish_web filters on Kish (logic) and therefore a modification of the value of Kish _Web. However, this doesn't cause any "cleaning" on collected variables with a filter on Kish_Web. 

In concrete terms, cleaning must be recursive to ensure the transitivity of the clearing of linked variables. 

There are 2 approaches to ensure this, affecting either Lunatic or Eno: 

* Lunatic: as soon as a variable is cleaned, make sure to execute the cleaning on the child variables if they are also present in "cleaning".
example: 
```json
{
	"cleaning": {
		"Kish": {
			"Kish_web": "vtl expression .dependent on Kish".
		},
		"Kish_web": {
			"Kish_telephone": "vtl expression dependent on Kish_web"
		}
	}
} 
```
When there is a Kish cleaning, run Kish_web cleaning 

* Eno: add the cleaning expressions of the children to the cleaning of the parent variable
The previous example would become 
```json
{
	"cleaning": {
		"Kish": {
			"Kish_web": "vtl expression .dependent on Kish",
			"Kish_telephone": "vtl expression dependent on Kish_web"
		},
		"Kish_web": {
			"Kish_telephone": "vtl expression dependent on Kish_web"
		}
	}
} 
```

This approach has one disadvantage: you need to run the Kish_web cleaning and have the new kish_web value to run the Kish_telephone expression. There is therefore an order to be respected, with something implicit in the model

**Comment by AnneHuSKa** [comment]
So we could have pb in all questionnaires (as soon as the design of filters is made.... "step by step") ?
Pb of collected data and of navigation (for instance VPP) ?
  
Are we ok that if we have :
 ```
  "cleaning": {
    "KT": {
      "Q4": "(K= \"2\") and (KW =\"2\") and (KT = \"1\")",
      "PROXY": "(K= \"2\") and (KW =\"2\") and (KT = \"2\")"
    },
    "K": {
      "Q4": "(K= \"2\") and (KW =\"2\") and (KT = \"1\")",
      "PROXY": "(K= \"2\") and (KW =\"2\") and (KT = \"2\")",
      "KT": "(K= \"2\") and (KW =\"2\")",
      "KW": "(K= \"2\")"
    },
    "KW": {
      "Q4": "(K= \"2\") and (KW =\"2\") and (KT = \"1\")",
      "PROXY": "(K= \"2\") and (KW =\"2\") and (KT = \"2\")",
      "KT": "(K= \"2\") and (KW =\"2\")"
    }
 ```
instead of
```  
  "cleaning": {
    "KT": {
      "Q4": "(KT = \"1\")",
      "PROXY": "(KT = \"2\")"
    },
    "K": {
      "KW": "(K= \"2\")"
    },
    "KW": {
      "KT": "(KW =\"2\")"
    }
```
it solves the pb ?


![image](https://github.com/InseeFr/Lunatic/assets/71011059/761a8369-b012-42ae-8fb8-cecb9b8558e8)

instead of 
![image](https://github.com/InseeFr/Lunatic/assets/71011059/d9e66cb3-a77d-4066-baa6-922cd5ef9c83)

?

We have to solve it by, a minima, we have to add a tip for "designing filters" ?

**Comment by ddecrulle** [comment]
Yes, you're absolutely right, that should solve the problem. Does it?

**Comment by AnneHuSKa** [comment]
Testée sur questionnaires basiques : pour ma part, tout ok, hormis donc souci cleaning

**Comment by laurentC35** [comment]
Closed (done in Sprint)
