### ISSUE TITLE
Pairwise - révision Liens deux à deux

### ISSUE THREAD

**Issue by AnneHuSKa** [InseeFr/Lunatic#838]
## Feature Description

Feedback (MOAE) : the links are not very easy to use, you don't "just" know which links are already filled in.

## Use Case

WIP

## Priority

Low

**Comment by jdirand** [comment]
I have received also some feedback on the pairwise links when users were testing the census form.
The more links they have, the more it gets difficults to see which one is already filled in, especially also because they are all displayed on 1 page. I also received some questions around why we were asking twice the links when they are symmetric ( aka conjoint / conjoint)

The questions we should ask ourselves is :
- is it necessary to show the symmetric links
- could we display them differently, separately ?

**Comment by AnneHuSKa** [comment]
https://github.com/InseeFr/Lunatic/issues/892
